export const WORKFLOW_STATES = {
  CONSULTATION: "CONSULTATION",
  LAB_ORDERED: "LAB_ORDERED",
  LAB_COMPLETED: "LAB_COMPLETED",
  PRESCRIPTION_CREATED: "PRESCRIPTION_CREATED",
  DISPENSED: "DISPENSED",
  BILLED: "BILLED",
  PAID: "PAID",
};

export const WORKFLOW_TRANSITIONS = {
  CONSULTATION: ["LAB_ORDERED", "PRESCRIPTION_CREATED"],
  LAB_ORDERED: ["LAB_COMPLETED"],
  LAB_COMPLETED: ["PRESCRIPTION_CREATED"],
  PRESCRIPTION_CREATED: ["DISPENSED"],
  DISPENSED: ["BILLED"],
  BILLED: ["PAID"],
};
